//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maersk_Line
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public Container()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ContainerID { get; set; }
        public string ContainerName { get; set; }
        public string ContainerDescription { get; set; }
        public int ContainerAmount { get; set; }
        public double ContainerWeight { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
