//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maersk_Line
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public Ship()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ShipCode { get; set; }
        public string ShipName { get; set; }
        public string ShipDescription { get; set; }
        public int NumberOfContainersCarried { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
